name: putitoutthere check

on:
  pull_request:
    paths:
      - 'putitoutthere.toml'
      - 'package.json'
      - 'scripts/*/package.json'
      - '.github/workflows/release.yml'
      - '.github/workflows/check.yml'

jobs:
  putitoutthere-check:
    uses: thekevinscott/putitoutthere/.github/workflows/check.yml@v0
