name: secr-b
on: pull_request
jobs:
  secr-b-bare:
    if: secrets.WILLFIRE_SECR_B != ''
    runs-on: ubuntu-latest
    steps:
      - run: 'true'
  secr-b-sibling:
    runs-on: ubuntu-latest
    steps:
      - run: 'true'
